# Owned config - Noctalia revamp
# Variables shared by the rest of ~/.config/hypr/peter

$mainMod = SUPER
$term = kitty --single-instance
$files = thunar
$scriptsDir = $HOME/.config/hypr/peter/scripts
$noctalia = noctalia msg
