# Owned config - decorations (colors are hardcoded, wallust removed)

general {
  border_size = 1
  gaps_in = 4
  gaps_out = 6

  col.active_border = rgb(E171A2)
  col.inactive_border = rgb(D6528B)
}

decoration {
  rounding = 10

  active_opacity = 1.0
  inactive_opacity = 0.9
  fullscreen_opacity = 1.0

  dim_inactive = true
  dim_strength = 0.1
  dim_special = 0.8

  shadow {
    enabled = true
    range = 1
    render_power = 1

    color = rgb(E171A2)
    color_inactive = rgb(D6528B)
  }

  blur {
    enabled = true
    size = 6
    passes = 3
    xray = true
    ignore_opacity = true
    special = true
    popups = true
  }
}

group {
  col.border_active = rgb(A9A769)

  groupbar {
    col.active = rgb(1C1C1B)
  }
}
